apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-ebf6b2af25d84b28ae997eb6a5034ffb-depl
  labels:
    app: coll-ebf6b2af25d84b28ae997eb6a5034ffb
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-ebf6b2af25d84b28ae997eb6a5034ffb
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-ebf6b2af25d84b28ae997eb6a5034ffb
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-ebf6b2af25d84b28ae997eb6a5034ffb
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-ebf6b2af25d84b28ae997eb6a5034ffb
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping