apiVersion: v1
kind: Service
metadata:
  name: coll-ebf6b2af25d84b28ae997eb6a5034ffb-srv
spec:
  selector:
    app: coll-ebf6b2af25d84b28ae997eb6a5034ffb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP